insert into big_job_tb(bigname) values("직군전체");
insert into big_job_tb(bigname) values("개발");
insert into big_job_tb(bigname) values("경영,비즈니스");
insert into big_job_tb(bigname) values("마케팅,광고");
insert into big_job_tb(bigname) values("디자인");
insert into big_job_tb(bigname) values("영업");
insert into big_job_tb(bigname) values("고객서비스,리테일");
insert into big_job_tb(bigname) values("미디어");
insert into big_job_tb(bigname) values("엔지니어링,설계");
insert into big_job_tb(bigname) values("게임제작");
insert into big_job_tb(bigname) values("HR");
insert into big_job_tb(bigname) values("금융");
insert into big_job_tb(bigname) values("제조,생산");
insert into small_job_tb(smallname,bigjobid) values("개발전체",2);
insert into small_job_tb(smallname,bigjobid) values("소프트웨어 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("웹 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("서버 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("프론트엔드 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("자바 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("C,C++ 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("파이썬 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("Node.js 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("데이터 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("안드로이드 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("DevOps/시스템 관리자",2);
insert into small_job_tb(smallname,bigjobid) values("IOS 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("시스템,네트워크 관리자",2);
insert into small_job_tb(smallname,bigjobid) values("개발 매니저",2);
insert into small_job_tb(smallname,bigjobid) values("QA,테스트 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("기술지원",2);
insert into small_job_tb(smallname,bigjobid) values("데이터 사이언티스트",2);
insert into small_job_tb(smallname,bigjobid) values("임베디드 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("보안 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("빅데이터 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("하드웨어 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("프로덕트 매니저",2);
insert into small_job_tb(smallname,bigjobid) values("블록체인 플랫폼 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("크로스플랫폼 앱 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("DBA",2);
insert into small_job_tb(smallname,bigjobid) values("PHP 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("웹 퍼블리셔",2);
insert into small_job_tb(smallname,bigjobid) values(".NET 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("영상,음성 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("ERP전문가",2);
insert into small_job_tb(smallname,bigjobid) values("그래픽스 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("CTO,Chief Technology",2);
insert into small_job_tb(smallname,bigjobid) values("VR 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("BI 엔지니어",2);
insert into small_job_tb(smallname,bigjobid) values("루비온레일즈 개발자",2);
insert into small_job_tb(smallname,bigjobid) values("CIO,Chief Information",2);
insert into small_job_tb(smallname,bigjobid) values("경영 비즈니스 전체",3);
insert into small_job_tb(smallname,bigjobid) values("PM,PO",3);
insert into small_job_tb(smallname,bigjobid) values("사업개발,기획자",3);
insert into small_job_tb(smallname,bigjobid) values("서비스 기획자",3);
insert into small_job_tb(smallname,bigjobid) values("전략 기획자",3);
insert into small_job_tb(smallname,bigjobid) values("경영지원",3);
insert into small_job_tb(smallname,bigjobid) values("운영 매니저",3);
insert into small_job_tb(smallname,bigjobid) values("회계,경리",3);
insert into small_job_tb(smallname,bigjobid) values("데이터 분석가",3);
insert into small_job_tb(smallname,bigjobid) values("해외 사업개발,기획자",3);
insert into small_job_tb(smallname,bigjobid) values("총무",3);
insert into small_job_tb(smallname,bigjobid) values("상품기획자(BM)",3);
insert into small_job_tb(smallname,bigjobid) values("자금담당",3);
insert into small_job_tb(smallname,bigjobid) values("컨설턴트",3);
insert into small_job_tb(smallname,bigjobid) values("사무보조",3);
insert into small_job_tb(smallname,bigjobid) values("오피스 관리",3);
insert into small_job_tb(smallname,bigjobid) values("조직관리",3);
insert into small_job_tb(smallname,bigjobid) values("정보보호 담당자",3);
insert into small_job_tb(smallname,bigjobid) values("ISMS(정보보호체계)",3);
insert into small_job_tb(smallname,bigjobid) values("구매담당",3);
insert into small_job_tb(smallname,bigjobid) values("경영 혁신가",3);
insert into small_job_tb(smallname,bigjobid) values("비서",3);
insert into small_job_tb(smallname,bigjobid) values("리스크 관리 전문가",3);
insert into small_job_tb(smallname,bigjobid) values("지역 관리 매니저",3);
insert into small_job_tb(smallname,bigjobid) values("CFO,Choef Financial",3);
insert into small_job_tb(smallname,bigjobid) values("전시 기획자",3);
insert into small_job_tb(smallname,bigjobid) values("공연 기획자",3);
insert into small_job_tb(smallname,bigjobid) values("COO,Cheif Operation",3);
insert into small_job_tb(smallname,bigjobid) values("CSO,Cheif statehy Of",3);
insert into small_job_tb(smallname,bigjobid) values("세미나/포럼기획자",3);
insert into small_job_tb(smallname,bigjobid) values("CEO",3);
insert into small_job_tb(smallname,bigjobid) values("안내원",3);
insert into small_job_tb(smallname,bigjobid) values("지점장",3);
insert into small_job_tb(smallname,bigjobid) values("에자일코치",3);
insert into small_job_tb(smallname,bigjobid) values("사내 심리상담가",3);
insert into small_job_tb(smallname,bigjobid) values("마케팅,광고 전체",4);
insert into small_job_tb(smallname,bigjobid) values("마케터",4);
insert into small_job_tb(smallname,bigjobid) values("디지털 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("콘테츠 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("퍼포먼스 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("마케팅 전략 기획자",4);
insert into small_job_tb(smallname,bigjobid) values("브랜드 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("광고 기획자(AE)",4);
insert into small_job_tb(smallname,bigjobid) values("글로벌 마케팅",4);
insert into small_job_tb(smallname,bigjobid) values("소셜 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("PR 전문가",4);
insert into small_job_tb(smallname,bigjobid) values("그로스 해커",4);
insert into small_job_tb(smallname,bigjobid) values("마케팅 디렉터",4);
insert into small_job_tb(smallname,bigjobid) values("카피라이터",4);
insert into small_job_tb(smallname,bigjobid) values("모바일마케팅",4);
insert into small_job_tb(smallname,bigjobid) values("키워드 공고",4);
insert into small_job_tb(smallname,bigjobid) values("마켓 리서치",4);
insert into small_job_tb(smallname,bigjobid) values("BTL 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("CMO",4);
insert into small_job_tb(smallname,bigjobid) values("ALT 마케터",4);
insert into small_job_tb(smallname,bigjobid) values("CBO",4);
insert into small_job_tb(smallname,bigjobid) values("Sports 전문가",4);
insert into small_job_tb(smallname,bigjobid) values("디자인 전체",5);
insert into small_job_tb(smallname,bigjobid) values("UX 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("UI,GUI 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("웹 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("그래픽 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("모바일 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("광고 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("제품 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("BI/BX 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("영상,모션 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("패키지 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("3D 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("아트 디렉터",5);
insert into small_job_tb(smallname,bigjobid) values("2D 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("패션 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("일러스트레이터",5);
insert into small_job_tb(smallname,bigjobid) values("공간 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("출판,편집 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("산업 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("인테리어 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("캐릭터 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("VMD",5);
insert into small_job_tb(smallname,bigjobid) values("전시 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("패브릭 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("가구 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("조경 디자이너",5);
insert into small_job_tb(smallname,bigjobid) values("영업 전체",6);
insert into small_job_tb(smallname,bigjobid) values("기업영업",6);
insert into small_job_tb(smallname,bigjobid) values("외부영업",6);
insert into small_job_tb(smallname,bigjobid) values("영업 관리자",6);
insert into small_job_tb(smallname,bigjobid) values("기술영업",6);
insert into small_job_tb(smallname,bigjobid) values("주요고객사 담당자",6);
insert into small_job_tb(smallname,bigjobid) values("해외영업",6);
insert into small_job_tb(smallname,bigjobid) values("솔루션 컨설턴트",6);
insert into small_job_tb(smallname,bigjobid) values("내부영업",6);
insert into small_job_tb(smallname,bigjobid) values("미디어 세일즈",6);
insert into small_job_tb(smallname,bigjobid) values("고객성공매니저",6);
insert into small_job_tb(smallname,bigjobid) values("세일즈 엔지니어",6);
insert into small_job_tb(smallname,bigjobid) values("의료기기영업",6);
insert into small_job_tb(smallname,bigjobid) values("제약영업",6);
insert into small_job_tb(smallname,bigjobid) values("고객서비스,리테일 전체",7);
insert into small_job_tb(smallname,bigjobid) values("MD",7);
insert into small_job_tb(smallname,bigjobid) values("서비스 운영",7);
insert into small_job_tb(smallname,bigjobid) values("CS매니저",7);
insert into small_job_tb(smallname,bigjobid) values("리테일MD",7);
insert into small_job_tb(smallname,bigjobid) values("CS 어드바이저",7);
insert into small_job_tb(smallname,bigjobid) values("패션 MD",7);
insert into small_job_tb(smallname,bigjobid) values("매장 관리자",7);
insert into small_job_tb(smallname,bigjobid) values("인바운드 텔레마케터",7);
insert into small_job_tb(smallname,bigjobid) values("CRM 전문가",7);
insert into small_job_tb(smallname,bigjobid) values("매장점원",7);
insert into small_job_tb(smallname,bigjobid) values("가맹점 관리자",7);
insert into small_job_tb(smallname,bigjobid) values("아웃바운드 텔레마케터",7);
insert into small_job_tb(smallname,bigjobid) values("이벤트 기획자",7);
insert into small_job_tb(smallname,bigjobid) values("AS 기술자",7);
insert into small_job_tb(smallname,bigjobid) values("리셉션",7);
insert into small_job_tb(smallname,bigjobid) values("비주얼머천다이저",7);
insert into small_job_tb(smallname,bigjobid) values("여행 에이전트",7);
insert into small_job_tb(smallname,bigjobid) values("헬스케어매니저",7);
insert into small_job_tb(smallname,bigjobid) values("승무원",7);
insert into small_job_tb(smallname,bigjobid) values("플로리스트",7);
insert into small_job_tb(smallname,bigjobid) values("피부관리",7);
insert into small_job_tb(smallname,bigjobid) values("헤어 디자이너",7);
insert into small_job_tb(smallname,bigjobid) values("미용사",7);
insert into small_job_tb(smallname,bigjobid) values("애견 미용사",7);
insert into small_job_tb(smallname,bigjobid) values("미디어 전체",8);
insert into small_job_tb(smallname,bigjobid) values("콘텐츠 크리에이터",8);
insert into small_job_tb(smallname,bigjobid) values("PD",8);
insert into small_job_tb(smallname,bigjobid) values("영상 편집가",8);
insert into small_job_tb(smallname,bigjobid) values("비디오 제작",8);
insert into small_job_tb(smallname,bigjobid) values("에디터",8);
insert into small_job_tb(smallname,bigjobid) values("연예,엔터테인먼트",8);
insert into small_job_tb(smallname,bigjobid) values("작가",8);
insert into small_job_tb(smallname,bigjobid) values("통,번역",8);
insert into small_job_tb(smallname,bigjobid) values("사진작가",8);
insert into small_job_tb(smallname,bigjobid) values("라이센스 관리자",8);
insert into small_job_tb(smallname,bigjobid) values("출판 기획자",8);
insert into small_job_tb(smallname,bigjobid) values("큐레이터",8);
insert into small_job_tb(smallname,bigjobid) values("저널리스트",8);
insert into small_job_tb(smallname,bigjobid) values("음향 엔지니어",8);
insert into small_job_tb(smallname,bigjobid) values("리포터",8);
insert into small_job_tb(smallname,bigjobid) values("엔지니어링,설계 전체",9);
insert into small_job_tb(smallname,bigjobid) values("전자 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("기계 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("로봇,자동화",9);
insert into small_job_tb(smallname,bigjobid) values("전기 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("CAD,3D 설계자",9);
insert into small_job_tb(smallname,bigjobid) values("제품 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("전기기계 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("제어 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("QA 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("설비 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("장비 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("프로젝트 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("공정 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("자동차 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("도면 담당자",9);
insert into small_job_tb(smallname,bigjobid) values("산업 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("QC 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("건설 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("도면 작성가",9);
insert into small_job_tb(smallname,bigjobid) values("인허가 담당 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("항공우주 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("화학공학 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("환경 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("RF 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("토목기사",9);
insert into small_job_tb(smallname,bigjobid) values("환경 안전기사",9);
insert into small_job_tb(smallname,bigjobid) values("자리정보시스템",9);
insert into small_job_tb(smallname,bigjobid) values("보건안전 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("구조공학 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("보일러 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("시니어 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("플렌트 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("전자계전 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("고압설계 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("생산공학 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("재료공학자",9);
insert into small_job_tb(smallname,bigjobid) values("사업수주 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("회전기계 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("농업 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("유전 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("생물의학자",9);
insert into small_job_tb(smallname,bigjobid) values("세라믹 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("시추 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("소방안전 기술자",9);
insert into small_job_tb(smallname,bigjobid) values("지리학자",9);
insert into small_job_tb(smallname,bigjobid) values("지질공학자",9);
insert into small_job_tb(smallname,bigjobid) values("I&C 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("해양공학자",9);
insert into small_job_tb(smallname,bigjobid) values("금속 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("광산 기술자",9);
insert into small_job_tb(smallname,bigjobid) values("광산 안전 기술자",9);
insert into small_job_tb(smallname,bigjobid) values("산업 공학자",9);
insert into small_job_tb(smallname,bigjobid) values("원자력 에너지",9);
insert into small_job_tb(smallname,bigjobid) values("석유공학 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("배관설계 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("플라스틱 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("저수처리 엔지니어",9);
insert into small_job_tb(smallname,bigjobid) values("터빈공학자",9);
insert into small_job_tb(smallname,bigjobid) values("게임 제작 전체",10);
insert into small_job_tb(smallname,bigjobid) values("게임 그래픽 디자이너",10);
insert into small_job_tb(smallname,bigjobid) values("게임 아티스트",10);
insert into small_job_tb(smallname,bigjobid) values("게임 기획자",10);
insert into small_job_tb(smallname,bigjobid) values("게임 클라이언트 개발자",10);
insert into small_job_tb(smallname,bigjobid) values("유니티 개발자",10);
insert into small_job_tb(smallname,bigjobid) values("모바일 게임 개발자",10);
insert into small_job_tb(smallname,bigjobid) values("게임 서버 개발자",10);
insert into small_job_tb(smallname,bigjobid) values("언리얼 개발자",10);
insert into small_job_tb(smallname,bigjobid) values("게임운영자(GM)",10);
insert into small_job_tb(smallname,bigjobid) values("HR 전체",11);
insert into small_job_tb(smallname,bigjobid) values("인사담당",11);
insert into small_job_tb(smallname,bigjobid) values("조직문화",11);
insert into small_job_tb(smallname,bigjobid) values("리크루터",11);
insert into small_job_tb(smallname,bigjobid) values("평가,보상",11);
insert into small_job_tb(smallname,bigjobid) values("HRD",11);
insert into small_job_tb(smallname,bigjobid) values("급여담당",11);
insert into small_job_tb(smallname,bigjobid) values("HRBP",11);
insert into small_job_tb(smallname,bigjobid) values("노무,노사",11);
insert into small_job_tb(smallname,bigjobid) values("헤트헌터",11);
insert into small_job_tb(smallname,bigjobid) values("HR 컨설턴트",11);
insert into small_job_tb(smallname,bigjobid) values("사내 강사",11);
insert into small_job_tb(smallname,bigjobid) values("기술 교육",11);
insert into small_job_tb(smallname,bigjobid) values("E-러닝",11);
insert into small_job_tb(smallname,bigjobid) values("교사",11);
insert into small_job_tb(smallname,bigjobid) values("교수",11);
insert into small_job_tb(smallname,bigjobid) values("금융 전체",12);
insert into small_job_tb(smallname,bigjobid) values("재무 담당자",12);
insert into small_job_tb(smallname,bigjobid) values("회계담당",12);
insert into small_job_tb(smallname,bigjobid) values("투자,증권",12);
insert into small_job_tb(smallname,bigjobid) values("IR",12);
insert into small_job_tb(smallname,bigjobid) values("재무 분석가",12);
insert into small_job_tb(smallname,bigjobid) values("내부통제 담당자",12);
insert into small_job_tb(smallname,bigjobid) values("애널리스트",12);
insert into small_job_tb(smallname,bigjobid) values("자산운용가",12);
insert into small_job_tb(smallname,bigjobid) values("공인회계사",12);
insert into small_job_tb(smallname,bigjobid) values("부동산 자산 관리자",12);
insert into small_job_tb(smallname,bigjobid) values("트레이더",12);
insert into small_job_tb(smallname,bigjobid) values("준법감시인",12);
insert into small_job_tb(smallname,bigjobid) values("부동산 중개사",12);
insert into small_job_tb(smallname,bigjobid) values("세무사",12);
insert into small_job_tb(smallname,bigjobid) values("금융공학자",12);
insert into small_job_tb(smallname,bigjobid) values("자산관리사",12);
insert into small_job_tb(smallname,bigjobid) values("투자은행가",12);
insert into small_job_tb(smallname,bigjobid) values("손해 사정관",12);
insert into small_job_tb(smallname,bigjobid) values("청구 담당자",12);
insert into small_job_tb(smallname,bigjobid) values("보험 에이전트",12);
insert into small_job_tb(smallname,bigjobid) values("계리사",12);
insert into small_job_tb(smallname,bigjobid) values("언더라이터",12);
insert into small_job_tb(smallname,bigjobid) values("감정평가사",12);
insert into small_job_tb(smallname,bigjobid) values("제조,생산 전체",13);
insert into small_job_tb(smallname,bigjobid) values("품질 관리자",13);
insert into small_job_tb(smallname,bigjobid) values("생산 관리자",13);
insert into small_job_tb(smallname,bigjobid) values("자재관리,구매",13);
insert into small_job_tb(smallname,bigjobid) values("기계,설비 설계",13);
insert into small_job_tb(smallname,bigjobid) values("제조 엔지니어",13);
insert into small_job_tb(smallname,bigjobid) values("섬유,의류,패션",13);
insert into small_job_tb(smallname,bigjobid) values("공정 관리자",13);
insert into small_job_tb(smallname,bigjobid) values("생산직 종사자",13);
insert into small_job_tb(smallname,bigjobid) values("안전 관리자",13);
insert into small_job_tb(smallname,bigjobid) values("기계제작 기술자",13);
insert into small_job_tb(smallname,bigjobid) values("반도체,디스플레이",13);
insert into small_job_tb(smallname,bigjobid) values("조립 기술자",13);
insert into small_job_tb(smallname,bigjobid) values("화학자",13);
insert into small_job_tb(smallname,bigjobid) values("제조 테스트 엔지니어",13);

insert into skill_tb(skill_name) values ("java");
insert into skill_tb(skill_name) values ("mysql");
insert into skill_tb(skill_name) values ("kotlin");
insert into skill_tb(skill_name) values ("python");
insert into skill_tb(skill_name) values ("C#");
insert into skill_tb(skill_name) values ("C++");
insert into skill_tb(skill_name) values ("C");
insert into skill_tb(skill_name) values ("Golang");
insert into skill_tb(skill_name) values ("Firebase");

insert into edu_tb(edu_name) values("중학교 졸업");
insert into edu_tb(edu_name) values("고등학교 재학");
insert into edu_tb(edu_name) values("고등학교 졸업");
insert into edu_tb(edu_name) values("대학교 재학");
insert into edu_tb(edu_name) values("대학교 휴학");
insert into edu_tb(edu_name) values("대학교 졸업 예정");
insert into edu_tb(edu_name) values("대학교 졸업");
insert into edu_tb(edu_name) values("석사");
insert into edu_tb(edu_name) values("박사");